### ISSUE TITLE
Debug build crashes with misaligned pointer dereference

### ISSUE THREAD

**Issue by DeltaF1** [Meziu/realtime-audio#1]
Running this example on my n3dsxl with `cargo 3ds run` causes a panic:
`misaligned pointer dereference: address must be a multiple of 0x8 but is 0x6150b4`

The file referenced is `rust/library/std/src/common/thread_local/mod.rs:46:22` but I don't have a full backtrace.

Very possible that there's something wrong with my environment, but so far I've been successfully building+running my own code and the examples from ctru-rs.

**Comment by Meziu** [comment]
I have no such issue on the latest release of all the packages.

Try:
- Pulling the latest changes from this repository (I've just now updated it)
- `rustup update`
- `cargo clean` in the repo
- `cargo update` in the repo
- Build with `--release` (decoding is too slow in debug mode, so you won't hear a thing regardless)

If it still doesn't work, try updating the `3ds-dev` packages via dkp's pacman.

**Comment by DeltaF1** [comment]
I completed all those steps other than enabling release mode, and it still had the same crash. I then built with --release and it's working fine. I now see this https://github.com/rust-lang/rust/pull/98112 so I guess that the misaligned pointer is only being caught because debug mode is enabled.
